/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/nissan_skyline_gtr_r33_nismo__www.vecarz.com.glb 
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nissan-skyline-gtr-r33-nismo-wwwvecarzcom-ac8e5d56f05d4b7aa75ba3a3b6d68920
Title: Nissan Skyline GTR R33 NISMO | www.vecarz.com
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "models/nissan_skyline_gtr_r33_nismo__www.vecarz.com.glb"
  );
  return (
    <group {...props} dispose={null} position={[0, -1, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.5}>
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.engine_paint}
        />
        <mesh geometry={nodes.Object_8.geometry} material={materials.base} />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995SeatBelt_Material}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.glassBackLight}
        />
        <mesh geometry={nodes.Object_14.geometry} material={materials.None} />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.engine_steel}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.engine_texture}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.titanium_pipe}
        />
        <mesh geometry={nodes.Object_22.geometry} material={materials.window} />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Grille6A_Material}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.lightFront}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.knalpot}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995BadgeA_Material}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Coloured_Material}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Coloured_Material}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={
            materials.Nissan_SkylineR33NismoSTune_1995InteriorA_Material
          }
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={
            materials.Nissan_SkylineR33NismoSTune_1995InteriorA_Material
          }
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={
            materials.Nissan_SkylineR33NismoSTune_1995InteriorTillingColourZo_536c238
          }
        />
        <mesh geometry={nodes.Object_42.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.body} />
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Carbon2_Material}
        />
        <mesh geometry={nodes.Object_48.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.body} />
        <mesh
          geometry={nodes.Object_68.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Grille2A_Material}
        />
        <mesh geometry={nodes.Object_70.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.disc} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.disc} />
        <mesh
          geometry={nodes.Object_82.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_84.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_86.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_88.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_90.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Grille3A_Material}
        />
        <mesh geometry={nodes.Object_92.geometry} material={materials.base} />
        <mesh geometry={nodes.Object_94.geometry} material={materials.baut} />
        <mesh
          geometry={nodes.Object_96.geometry}
          material={materials["baut.001"]}
        />
        <mesh geometry={nodes.Object_98.geometry} material={materials.badge} />
        <mesh
          geometry={nodes.Object_100.geometry}
          material={materials.sidewall}
        />
        <mesh
          geometry={nodes.Object_102.geometry}
          material={materials.sidewall}
        />
        <mesh
          geometry={nodes.Object_104.geometry}
          material={materials.sidewall}
        />
        <mesh
          geometry={nodes.Object_106.geometry}
          material={materials.sidewall}
        />
        <mesh
          geometry={nodes.Object_108.geometry}
          material={materials.spoiler}
        />
        <mesh
          geometry={nodes.Object_110.geometry}
          material={materials.spoiler_dark}
        />
        <mesh
          geometry={nodes.Object_112.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Grille4A_Material}
        />
        <mesh
          geometry={nodes.Object_114.geometry}
          material={materials.spoiler_dark}
        />
        <mesh geometry={nodes.Object_116.geometry} material={materials.spoke} />
        <mesh geometry={nodes.Object_118.geometry} material={materials.spoke} />
        <mesh geometry={nodes.Object_120.geometry} material={materials.spoke} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.spoke} />
        <mesh
          geometry={nodes.Object_124.geometry}
          material={materials.plastic}
        />
        <mesh
          geometry={nodes.Object_126.geometry}
          material={materials.plastic}
        />
        <mesh
          geometry={nodes.Object_128.geometry}
          material={materials.material_28}
        />
        <mesh
          geometry={nodes.Object_130.geometry}
          material={materials.material_28}
        />
        <mesh
          geometry={nodes.Object_132.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Grille5A_Material}
        />
        <mesh
          geometry={nodes.Object_134.geometry}
          material={materials.Nissan_SkylineR33NismoSTune_1995Grille7A_Material}
        />
        <mesh
          geometry={nodes.Object_136.geometry}
          material={
            materials.Nissan_SkylineR33NismoSTune_1995LicensePlateDefaultA_Material
          }
        />
      </group>
      <group position={[0.036, 0.2, 0.015]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_140.geometry}
          material={materials["glass.001"]}
          position={[-0.035, 0.014, -0.2]}
        />
      </group>
      <mesh
        geometry={nodes.Object_144.geometry}
        material={
          materials["Nissan_SkylineR33NismoSTune_1995Window_Material.001"]
        }
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/nissan_skyline_gtr_r33_nismo__www.vecarz.com.glb");
